/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
* @author Harshal Kudale , //Modeified version of paul oamen.
* */

package StudentDBMysql;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;
import java.text.MessageFormat;
import java.util.Vector;


public class StudentDBMysql extends javax.swing.JFrame {
    private static final String username="root"; // MySQL username
    private static final String password="root"; // MySQl password
    private static final String dataConn ="jdbc:mysql://localhost:3306/studentdata";  // JDBC connector
    Connection sqlConn =null;
    PreparedStatement pst = null;
    ResultSet rs=null;
    int q, i, deleteItem,studid;
    String studentId, firstName, surName, address, mobile, gender, isMaths, isGames, isScience, isDataSci, isAnalysis, isGraphic, isEnglish, isDatabase;
    /**
     * Creates new form StudentDBMysql
     */
    public StudentDBMysql() {
        // Constructor to call automatically on start
        initComponents(); // Initialize Components
        updateDB(); // Update JTable from database function
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //===============================Starter Function Declaration======================================
    //UpdateDB definition
    public boolean updateDB() {
        boolean check;
        //int q, i;
         try
        {
           
           Class.forName("com.mysql.cj.jdbc.Driver"); 
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("select * from studentdata");
            
            rs =pst.executeQuery();
            ResultSetMetaData StData = rs.getMetaData();
            
            q = StData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                
                Vector columnData = new Vector();
                
                for (i = 1; i <= q; i++)
                {
                    //columnData.add(rs.getString("id"));
                    columnData.add(rs.getString("studentid"));
                    columnData.add(rs.getString("firstname"));
                    columnData.add(rs.getString("surname"));
                    columnData.add(rs.getString("address"));
                    columnData.add(rs.getString("gender"));
                    columnData.add(rs.getString("mobile"));
                    columnData.add(rs.getString("maths"));
                    columnData.add(rs.getString("games"));
                    columnData.add(rs.getString("datasci"));
                    columnData.add(rs.getString("analysis"));
                    columnData.add(rs.getString("graphic"));
                    columnData.add(rs.getString("database1"));
                    columnData.add(rs.getString("science"));
                    columnData.add(rs.getString("english"));
                }
                    RecordTable.addRow(columnData);                
                
            }
            check = true;
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            check =  false;
        }
         return check;
    }
    //Initialize components definition
    protected void initComponents() {

        JPanel jPanel2 = new JPanel();
        JPanel jPanel4 = new JPanel();
        JLabel jLabel15 = new JLabel();
        JPanel jPanel5 = new JPanel();
        JPanel jPanel1 = new JPanel();
        JScrollPane jScrollPane1 = new JScrollPane();
        jTable1 = new javax.swing.JTable();
        JPanel jPanel7 = new JPanel();
        JLabel jLabel1 = new JLabel();
        JLabel jLabel2 = new JLabel();
        JLabel jLabel3 = new JLabel();
        JLabel jLabel4 = new JLabel();
        JLabel jLabel5 = new JLabel();
        JLabel jLabel6 = new JLabel();
        txtFirstname = new javax.swing.JTextField();
        txtStudentID = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        cboGender = new javax.swing.JComboBox<>();
        JPanel jPanel3 = new JPanel();
        JLabel jLabel7 = new JLabel();
        JLabel jLabel8 = new JLabel();
        JLabel jLabel9 = new JLabel();
        JLabel jLabel10 = new JLabel();
        cboGraphic = new javax.swing.JComboBox<>();
        cboDatabase = new javax.swing.JComboBox<>();
        cboScience = new javax.swing.JComboBox<>();
        cboEnglish = new javax.swing.JComboBox<>();
        JPanel jPanel8 = new JPanel();
        JLabel jLabel11 = new JLabel();
        cboMaths = new javax.swing.JComboBox<>();
        cboGames = new javax.swing.JComboBox<>();
        JLabel jLabel12 = new JLabel();
        JLabel jLabel13 = new JLabel();
        JLabel jLabel14 = new JLabel();
        cboAnalysis = new javax.swing.JComboBox<>();
        cboDataSci = new javax.swing.JComboBox<>();
        JPanel jPanel6 = new JPanel();
        JButton btnPrint = new JButton();
        JButton btnUpdate = new JButton();
        JButton btnReset = new JButton();
        JButton btnDelete = new JButton();
        JButton btnExit = new JButton();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton btnAddNew = new JButton();
        JPanel jPanel9 = new JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1360, 735));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 51, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setFont(new java.awt.Font("Tahoma", Font.BOLD, 48)); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(0, 153, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", Font.BOLD, 60)); // NOI18N
        jLabel15.setText("Student Record Management using JAVA");
        jLabel15.setToolTipText("");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1340, 90));

        jPanel5.setBackground(new java.awt.Color(255, 102, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setFont(new java.awt.Font("Tahoma", Font.BOLD, 48)); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(153, 255, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Firstname", "Surname", "Address", "Gender", "Mobile", "Maths", "Games", "Data Sci", "Analysis", "Graphic", "Database", "Science", "English"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked();
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, 450));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 890, 470));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel1.setText("Mobile");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel2.setText("Student ID");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel3.setText("Firstname");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel4.setText("Surname");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel5.setText("Address");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel6.setText("Gender");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        txtFirstname.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
        jPanel7.add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 270, -1));

        txtStudentID.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
        jPanel7.add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 270, -1));

        txtAddress.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
        jPanel7.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 270, -1));

        txtSurname.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
        jPanel7.add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 270, -1));

        txtMobile.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N

        jPanel7.add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 270, -1));

        cboGender.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 18)); // NOI18N
        cboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cboGender.setSelectedItem(cboGender);
        jPanel7.add(cboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 120, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setFont(new java.awt.Font("Tahoma", Font.BOLD, 48)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel7.setText("Graphic");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel8.setText("Database");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel9.setText("Science");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel10.setText("English");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        cboGraphic.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
        cboGraphic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes", "Core Unit", "Complete" }));
        jPanel3.add(cboGraphic, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 30));

        cboDatabase.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
        cboDatabase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes", "Core Unit", "Complete" }));
        jPanel3.add(cboDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 90, 30));

        cboScience.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
        cboScience.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes", "Core Unit", "Complete" }));
        jPanel3.add(cboScience, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 90, 30));

        cboEnglish.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
        cboEnglish.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes", "Core Unit", "Complete" }));
        jPanel3.add(cboEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, 30));

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 200, 190));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setFont(new java.awt.Font("Tahoma", Font.BOLD, 48)); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel11.setText("Maths");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        cboMaths.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
        cboMaths.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes", "Core Unit", "Complete" }));
        jPanel8.add(cboMaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 30));

        cboGames.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
        cboGames.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes", "Core Unit", "Complete" }));
        jPanel8.add(cboGames, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 90, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel12.setText("Games");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel13.setText("Data Sci");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", Font.BOLD, 18)); // NOI18N
        jLabel14.setText("Analysis");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        cboAnalysis.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
        cboAnalysis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes", "Core Unit", "Complete" }));
        jPanel8.add(cboAnalysis, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 90, 30));

        cboDataSci.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
        cboDataSci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes", "Core Unit", "Complete" }));
        jPanel8.add(cboDataSci, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 90, 30));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 200, 190));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 470));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrint.setBackground(new java.awt.Color(255, 255, 0));
        btnPrint.setFont(new java.awt.Font("Tahoma", Font.BOLD, 36)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(this::btnPrintActionPerformed);
        jPanel6.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 212, 60));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 0));
        btnUpdate.setFont(new java.awt.Font("Tahoma", Font.BOLD, 36)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(evt -> btnUpdateActionPerformed());
        jPanel6.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 212, 60));

        btnReset.setBackground(new java.awt.Color(255, 255, 0));
        btnReset.setFont(new java.awt.Font("Tahoma", Font.BOLD, 36)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(evt -> btnResetActionPerformed());
        jPanel6.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 212, 60));

        btnDelete.setBackground(new java.awt.Color(255, 255, 0));
        btnDelete.setFont(new java.awt.Font("Tahoma", Font.BOLD, 36)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(evt -> btnDeleteActionPerformed());
        jPanel6.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 212, 60));

        btnExit.setBackground(new java.awt.Color(255, 255, 0));
        btnExit.setFont(new java.awt.Font("Tahoma", Font.BOLD, 36)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(evt -> btnExitActionPerformed());
        jPanel6.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, 212, 60));

        btnAddNew.setBackground(new java.awt.Color(255, 255, 0));
        btnAddNew.setFont(new java.awt.Font("Tahoma", Font.BOLD, 36)); // NOI18N
        btnAddNew.setText("Add New");
        btnAddNew.addActionListener(evt -> btnAddNewActionPerformed());
        jPanel6.add(btnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 200, 60));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 1320, 80));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1340, 580));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 690));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 690, 770, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //===============================Action Function Declaration======================================
    // To assign fields to variables
    public void getFields(){
        studentId = txtStudentID.getText();
        firstName = txtFirstname.getText();
        surName = txtSurname.getText();
        address = txtAddress.getText();
        mobile = txtMobile.getText();
        gender = (String) cboGender.getSelectedItem();
        isMaths = (String)cboMaths.getSelectedItem();
        isGames = (String)cboGames.getSelectedItem();
        isScience = (String)cboScience.getSelectedItem();
        isAnalysis = (String)cboAnalysis.getSelectedItem();
        isDatabase = (String)cboDatabase.getSelectedItem();
        isDataSci = (String)cboDataSci.getSelectedItem();
        isGraphic = (String)cboGraphic.getSelectedItem();
        isEnglish = (String)cboEnglish.getSelectedItem();
    }
    // To reset fields
    public boolean resetRecords(){

        txtStudentID.setText("");
        txtFirstname.setText("");
        txtSurname.setText("");
        txtAddress.setText("");
        cboGender.setSelectedIndex(0);
        txtMobile.setText("");
        cboMaths.setSelectedIndex(0);
        cboGames.setSelectedIndex(0);
        cboDataSci.setSelectedIndex(0);
        cboAnalysis.setSelectedIndex(0);
        cboGraphic.setSelectedIndex(0);
        cboDatabase.setSelectedIndex(0);
        cboScience.setSelectedIndex(0);
        cboEnglish.setSelectedIndex(0);

        return true;
    }
    // To exit app
    public void exitApp(){
        // Jframe declaration
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","Student Management Systems",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }
    // To add new records in database
    public boolean addRecords(String id, String firstName, String surName, String address){
        boolean check = false;
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("insert into studentdata(studentid,firstname,surname,address,"
                    + "gender,mobile,maths,games,datasci,analysis,graphic,database1,science,english)values"
                    + "(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

            pst.setString(1, id);
            pst.setString(2, firstName);
            pst.setString(3, surName);
            pst.setString(4, address);
            pst.setString(5, gender);
            pst.setString(6, mobile);
            pst.setString(7, isMaths);
            pst.setString(8, isGames);
            pst.setString(9, isDataSci);
            pst.setString(10, isAnalysis);
            pst.setString(11, isGraphic);
            pst.setString(12, isDatabase);
            pst.setString(13, isScience);
            pst.setString(14, isEnglish);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Student Record Added");
            updateDB();
            check = true;
        }

        catch (ClassNotFoundException | SQLException ex) {
            java.util.logging.Logger.getLogger(StudentDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } //System.err.println(ex);

        return check;
    }
    // To update old fields with new values
    public boolean updateRecords(int studid,String id, String firstName, String surName, String address){
        boolean check=false;
        try
        {

            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("update studentdata set studentid =?,firstname=?,surname=?,"
                    + "address=?,gender=?,mobile=?,maths=?,games=?,datasci=?,analysis=?,graphic=?,"
                    + "database1=?,science=?,english=? where studentid =?");

            pst.setString(1, id);
            pst.setString(2, firstName);
            pst.setString(3, surName);
            pst.setString(4, address);
            pst.setString(5, gender);
            pst.setString(6, mobile);
            pst.setString(7, isMaths);
            pst.setString(8, isGames);
            pst.setString(9, isDataSci);
            pst.setString(10, isAnalysis);
            pst.setString(11, isGraphic);
            pst.setString(12, isDatabase);
            pst.setString(13, isScience);
            pst.setString(14, isEnglish);
            pst.setInt(15, studid);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Student Record updated");
            updateDB();
            check = true;
        }

        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            System.err.println(ex);
        }
        return check;
    }
    // To Print the table in PDF
    public boolean printRecords(){
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        boolean check=false;
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
            check = true;
        }

        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No Printer found", e.getMessage());
        }
        return check;
    }
    // To delete records from database
    public boolean deleteRecords(int studid){
        boolean check=false;
        try
        {


            //int deleteItem
            deleteItem = JOptionPane.showConfirmDialog(null,"Confirm if you want to delete item",
                    "Warning",JOptionPane.YES_NO_OPTION);
            if (deleteItem ==JOptionPane.YES_OPTION )
            {

                Class.forName("com.mysql.cj.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn,username,password);
                pst = sqlConn.prepareStatement("delete from studentdata where studentid =?");

                pst.setInt(1, studid);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Student Record Deleted");
                updateDB();

                txtStudentID.setText("");
                txtStudentID.requestFocus();
                txtFirstname.setText("");
                txtSurname.setText("");
                txtAddress.setText("");
                cboGender.setSelectedIndex(0);
                txtMobile.setText("");
                cboMaths.setSelectedIndex(0);
                cboGames.setSelectedIndex(0);
                cboDataSci.setSelectedIndex(0);
                cboAnalysis.setSelectedIndex(0);
                cboGraphic.setSelectedIndex(0);
                cboDatabase.setSelectedIndex(0);
                cboScience.setSelectedIndex(0);
                cboEnglish.setSelectedIndex(0);
            }
            check = true;
        }

        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDBMysql.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (SQLException ex) {
            System.err.println(ex);
        }
        return check;
    }

    //Button Click events
    private void btnResetActionPerformed() {//GEN-FIRST:event_btnResetActionPerformed
        resetRecords();
    }

    private void btnExitActionPerformed() {//GEN-FIRST:event_btnExitActionPerformed
        exitApp();
    }

    private void btnAddNewActionPerformed() {//GEN-FIRST:event_btnAddNewActionPerformed
        getFields();
        addRecords(studentId,firstName,surName,address);
    }

    private void btnUpdateActionPerformed() {//GEN-FIRST:event_btnUpdateActionPerformed
        getFields();
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        studid = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
        updateRecords(studid,studentId,firstName,surName,address);
    }

    private void jTable1MouseClicked() {//GEN-FIRST:event_jTable1MouseClicked
       
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        txtStudentID.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        txtFirstname.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        txtSurname.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        txtAddress.setText(RecordTable.getValueAt(SelectedRows, 3).toString());        
        cboGender.setSelectedItem(RecordTable.getValueAt(SelectedRows, 4).toString());        
        txtMobile.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        cboMaths.setSelectedItem(RecordTable.getValueAt(SelectedRows, 6).toString());
        cboGames.setSelectedItem(RecordTable.getValueAt(SelectedRows, 7).toString());
        cboDataSci.setSelectedItem(RecordTable.getValueAt(SelectedRows, 8).toString());
        cboAnalysis.setSelectedItem(RecordTable.getValueAt(SelectedRows, 9).toString());
        cboGraphic.setSelectedItem(RecordTable.getValueAt(SelectedRows, 10).toString());
        cboDatabase.setSelectedItem(RecordTable.getValueAt(SelectedRows, 11).toString());
        cboScience.setSelectedItem(RecordTable.getValueAt(SelectedRows, 12).toString());
        cboEnglish.setSelectedItem(RecordTable.getValueAt(SelectedRows, 13).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        printRecords();
    }

    private void btnDeleteActionPerformed() {//GEN-FIRST:event_btnDeleteActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        studid = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
        deleteRecords(studid);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDBMysql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentDBMysql().setVisible(true));
    }

    private javax.swing.JComboBox<String> cboAnalysis;
    private javax.swing.JComboBox<String> cboDataSci;
    private javax.swing.JComboBox<String> cboDatabase;
    private javax.swing.JComboBox<String> cboEnglish;
    private javax.swing.JComboBox<String> cboGames;
    private javax.swing.JComboBox<String> cboGender;
    private javax.swing.JComboBox<String> cboGraphic;
    private javax.swing.JComboBox<String> cboMaths;
    private javax.swing.JComboBox<String> cboScience;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
